---
- name: install nginx web server
  apt: pkg=nginx state=installed
  become: True

- name: apply nginx server and virtualhost config templates
  template: src={{ item.src }} dest={{ item.dest }}  mode=0644 owner=root group=root
  become: True
  with_items:
    - { src: 'nginx.conf.j2', dest: '/etc/nginx/nginx.conf' }
    - { src : 'app.conf.j2', dest: '/etc/nginx/sites-enabled/app.conf' }
    - { src : 'www.conf.j2', dest: '/etc/php/7.0/fpm/pool.d/www.conf' }
    - { src : 'php.ini.j2', dest: '/etc/php/7.0/fpm/php.ini' }

- name: nix default nginx config
  file: dest=/etc/nginx/sites-enabled/default state=absent
  become: True

- name: chown html directory to be owned by www-data
  file: path=/usr/share/nginx/html owner=www-data group=www-data mode=0755
  become: True

- name: Remove nginx default web files
  file: path=/usr/share/nginx/html/{{item}} state=absent
  with_items:
    - index.html
    - 50x.html
  ignore_errors: yes
  become: True

- name: Make sure /var/www/.ssh exists
  file: path={{ item }} state=directory owner=www-data group=www-data mode=0755
  become: True
  with_items:
    - /var/www/.ssh

- name: restart web server
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - nginx
    - php7.0-fpm
  become: True