app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
    methods: ["GET"]

demo_index:
    path: /demo
    defaults: { _controller: AppBundle:Worker:demoIndex }
    methods: ["GET"]

process_email:
    path: /email
    defaults: { _controller: AppBundle:Worker:scheduleEmailWorker }
    methods: ["POST"]

job_status:
    path: /status/{jobId}
    defaults: { _controller: AppBundle:Worker:getWorkerStatus }
    methods: ["GET"]

job_data:
    path: /data/{jobId}
    defaults: { _controller: AppBundle:Worker:getWorkerData }
    methods: ["GET"]