services:
    service.data_broker:
        class: AppBundle\Job\DataBroker
        arguments: ["%redis_server%", "%redis_port%"]

    service.job_runner:
        class: AppBundle\Job\JobRunner
        arguments: ["%redis_server%", "%redis_port%", "@service.data_broker"]

    service.hacker_news:
        class: AppBundle\Service\HackerNewsService
        arguments: ["@client.guzzle"]

    client.guzzle:
        class: GuzzleHttp\Client

    util.data_broker:
        class: AppBundle\Job\DataBroker
        arguments: ["%redis_server%", "%redis_port%"]