---
- name: Ensure PPAs
  apt_repository: repo="{{ item }}"
  become: True
  with_items:
    - ppa:ondrej/php
    - ppa:ansible/ansible
  ignore_errors: True

- name: vim
  action: apt pkg=vim state=present
  become: True

- name: git
  action: apt pkg=git state=present
  become: True

- name: htop
  action: apt pkg=htop state=present
  become: True

- name: PHP 7
  action: apt pkg={{ item }} state=present
  with_items:
    - php7.0-common
    - php7.0
    - php7.0-dev
    - libreadline-dev
    - php7.0-readline
    - php7.0-gd
    - php7.0-curl
    - php7.0-mysql
    - php-apc
    - php7.0-cli
    - php7.0-intl
    - php7.0-mcrypt
    - php7.0-fpm
  become: True

- name: python-setuptools
  action: apt pkg=python-setuptools state=present
  become: True

- name: python-dev
  action: apt pkg=python-dev state=present
  become: True

- name: build-essential
  action: apt pkg=build-essential state=present
  become: True

- name: python-pip
  action: apt pkg=python-pip state=present
  become: True

- name: libmysqlclient-dev
  action: apt pkg=libmysqlclient-dev state=present
  become: True

- name: software-properties-common
  action: apt pkg=software-properties-common state=present
  become: True

- name: zip
  action: apt pkg=zip state=present
  become: True

- name: unzip
  action: apt pkg=unzip state=present
  become: True

- name: pip
  shell: easy_install pip
  become: True

- name: python-mysqldb
  action: apt pkg=python-mysqldb state=present
  become: True

- name: ansible
  action: apt pkg=ansible state=present
  become: True
  when: symfony_env == "dev"

- name: Ensure hosts file for DNS routing override
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
  become: True
  when: symfony_env == "dev"

- name: Ensure environment aware bash_profile for development
  template: src=.bash_profile.j2 dest=/home/vagrant/.bash_profile owner=vagrant group=vagrant mode=0655
  when: symfony_env == "dev"

- name: Ensure environment aware bash_profile for ubuntu
  template: src=.bash_profile.j2 dest=/home/ubuntu/.bash_profile owner=ubuntu group=ubuntu mode=0655
  when: symfony_env != "dev"

- name: Ensure environment aware bash_profile for ubuntu
  template: src=.bash_profile.j2 dest=/root/.bash_profile owner=root group=root mode=0655
  when: symfony_env != "dev"
  become: True

- name: move composer to appropriate location
  copy: src=composer.phar dest=/usr/local/bin/composer owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode="u+rwx,g+rx,o-rwx"
  become: True

- name: Ensure web directory permissions
  file: path=/var/www state=directory mode=0755 owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}
  become: True

- name: Ensure phpunit exists and is executable
  copy: src=phpunit.phar dest=/usr/local/bin/phpunit owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode="u+rwx,g+rx,o-rwx"
  become: True